export const PSC_TOPICS = [
  { label: 'Kerala History', value: 'Kerala History' },
  { label: 'Kerala Renaissance Leaders', value: 'Kerala Renaissance leaders' },
  { label: 'Social Reform Movements', value: 'Social Reform Movements in Kerala' },
  { label: 'United Kerala Movement', value: 'United Kerala Movement' },
  { label: 'Ancient & Medieval Indian History', value: 'Ancient and Medieval Indian History' },
  { label: 'Indian Freedom Struggle', value: 'Indian Freedom Struggle' },
  { label: 'Post-Independence India', value: 'Post-Independence India' },
  { label: 'World Revolutions', value: 'World Revolutions' },
  { label: 'World Wars', value: 'World Wars' },
  { label: 'Cultural Heritage of Kerala', value: 'Cultural Heritage of Kerala' },
  { label: 'Art Forms and Literature', value: 'Kerala Art Forms and Literature' },
  { label: 'Physiography of India', value: 'Physiography of India' },
  { label: 'Indian Rivers and Water Bodies', value: 'Indian Rivers and Water Bodies' },
  { label: 'Climate and Seasons of India', value: 'Climate and Seasons of India' },
  { label: 'Natural Vegetation and Agriculture in India', value: 'Natural Vegetation and Agriculture in India' },
  { label: 'Minerals and Industries in India', value: 'Minerals and Industries in India' },
  { label: 'Indian Transport Systems', value: 'Indian Transport Systems' },
  { label: 'Districts of Kerala', value: 'Districts of Kerala' },
  { label: 'Wildlife Sanctuaries & National Parks', value: 'Wildlife Sanctuaries and National Parks in Kerala' },
  { label: 'World Geography Basics', value: 'World Geography Basics' },
  { label: 'Oceans and Continents', value: 'Oceans and Continents' },
  { label: 'Indian Constitution: Preamble', value: 'Indian Constitution: Preamble' },
  { label: 'Fundamental Rights and Duties', value: 'Fundamental Rights and Duties in Indian Constitution' },
  { label: 'Directive Principles (DPSP)', value: 'Directive Principles of State Policy (DPSP)' },
  { label: 'Union and State Executives', value: 'Union and State Executives of India' },
  { label: 'Parliament and State Legislatures', value: 'Indian Parliament and State Legislatures' },
  { label: 'Indian Judiciary', value: 'Indian Judiciary' },
  { label: 'Local Self-Government Institutions (LSGIs)', value: 'Local Self-Government Institutions in India' },
  { label: 'Important Constitutional Amendments', value: 'Important Constitutional Amendments of India' },
  { label: 'Election Commission of India', value: 'Election Commission of India' },
  { label: 'Human Rights', value: 'Human Rights' },
  { label: 'Statutory & Quasi-judicial Bodies', value: 'Statutory and Quasi-judicial Bodies in India' },
  { label: 'Indian Economy Post-Reform', value: 'Indian Economy post-1991 reform' },
  { label: 'NITI Aayog', value: 'NITI Aayog' },
  { label: 'Five-Year Plans of India', value 'Five-Year Plans of India' },
  { label: 'Sectoral Composition of Indian Economy', value: 'Sectoral Composition of Indian Economy' },
  { label: 'Banking and Finance in India', value: 'Banking and Finance in India' },
  { label: 'Goods and Services Tax (GST)', value: 'Goods and Services Tax (GST)' },
  { label: 'Social Welfare Schemes in India', value: 'Social Welfare Schemes in India' },
  { label: 'Land Reforms in India', value: 'Land Reforms in India' },
  { label: 'Poverty and Unemployment in India', value: 'Poverty and Unemployment in India' },
  { label: 'Basic Physics', value: 'Basic Physics (Units, Motion, Force, Heat, Light, Sound)' },
  { label: 'Basic Chemistry', value: 'Basic Chemistry (Atoms, Periodic Table, Metals, Acids/Bases)' },
  { label: 'Basic Biology', value: 'Basic Biology (Human Body, Nutrition, Vitamins, Minerals)' },
  { label: 'Public Health', value: 'Public Health in India' },
  { label: 'Communicable & Lifestyle Diseases', value: 'Communicable and Lifestyle Diseases' },
  { label: 'Environment and Ecology', value: 'Environment and Ecology' },
  { label: 'Biodiversity', value: 'Biodiversity' },
  { label: 'Climate Change', value: 'Climate Change' },
  { label: 'Arithmetic & Mental Ability', value: 'Arithmetic and Mental Ability' },
  { label: 'General English', value: 'General English' },
  { label: 'IT & Cyber Laws', value: 'IT and Cyber Laws' },
  { label: 'Important Acts (RTI, RTE, etc.)', value: 'Important Acts in India (RTI, RTE, Consumer Protection)' },
  { label: 'Regional Language (Malayalam)', value: 'Malayalam Grammar and Vocabulary' },
  { label: 'Current Affairs', value: 'Current Affairs' },
];
